### ISSUE TITLE
This is exchange sort

### ISSUE THREAD

**Issue by Timeroot** [theshteves/simplest-sort#1]
As you wrote it down, this is exchange sort. To fix it and give the "strange" sort, you need to change two lines:
```
        for j in range(N):
            if data[i] < data[j]:
                data[i], data[j] = data[j], data[i]
```
you need to change it from `range(i, N)` to just `range(N)` (so that it loops over each pair of indices twice) and change it from `>` to `<` (so that it appears to be going the 'wrong way').

**Comment by theshteves** [comment]
Thanks for catching this, @Timeroot!

I didn't notice that I used Algorithm 2 instead of 1. **I just added all 3 implementations** while we're at it.

They only used 1-indexing in the paper for more intuitive demonstration, but I kept my implementation more Pythonic with 0-indexing.
